Repository wecode-bootcamp-korea/29-1st-Dr-Mataeng-backend, pull requests merged in 2022-01, with the labels that each got.

#5 [29기 강종범][Add] project modeling(users, products, orders)
  core/__init__.py
  core/admin.py
  core/apps.py
  core/migrations/__init__.py
  core/models.py
  core/tests.py
  core/views.py
  dr_mataeng/settings.py
  orders/__init__.py
  orders/admin.py
  orders/apps.py
  orders/migrations/0001_initial.py
  orders/migrations/__init__.py
  orders/models.py
  orders/tests.py
  orders/views.py
  products/__init__.py
  products/admin.py
  products/apps.py
  products/migrations/0001_initial.py
  products/migrations/__init__.py
  products/models.py
  products/tests.py
  products/views.py
  users/__init__.py
  users/admin.py
  users/apps.py
  users/migrations/0001_initial.py
  users/migrations/__init__.py
  users/models.py
  users/tests.py
  users/views.py
Labels: Status: Accepted

#6 [29기 강종범][Add] Signup(views.py, urls.py)
  dr_mataeng/urls.py
  orders/migrations/0001_initial.py
  products/migrations/0001_initial.py
  requirements.txt
  users/migrations/0001_initial.py
  users/models.py
  users/urls.py
  users/views.py
Labels: Status: 수정 요청

#7 [29기 이혜린][Add] Signin(views.py, urls.py)
  .gitignore
  requirements.txt
  users/urls.py
  users/views.py
Labels: Status: 리뷰 요청
